/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.typicaldev.sudoku

import kotlin.test.Test
import kotlin.test.assertTrue

class SudokuTest {
    @Test fun testSomeLibraryMethod() {

    }
}
